version: "3"
services:
  postgres:
    image: postgres:12
    environment:
      - POSTGRES_USER=puser
      - POSTGRES_PASSWORD=ppsw
      - POSTGRES_DB=lportal
    ports:
      - "20001:5432"
    volumes:
      - database-data:/var/lib/postgresql/data
    networks:
      - liferay-network
  liferay:
    image: liferay/portal:7.3.5-ga6
    depends_on:
      - postgres
    environment:
      - JPDA_ADDRESS=0.0.0.0:8000
      - LIFERAY_JPDA_ENABLED=true
    ports:
      - "20002:8080"
      - "20003:8000"
      - "20004:11311"
    volumes:
      - ./mount:/mnt/liferay
      - liferay-document-library:/opt/liferay/data/document_library
      - liferay-configs:/opt/liferay/osgi/configs
      - liferay-modules:/opt/liferay/osgi/modules
      - liferay-war:/opt/liferay/osgi/war
    networks:
      - liferay-network
volumes:
  database-data:
  liferay-document-library:
  liferay-configs:
  liferay-modules:
  liferay-war:
networks:
  liferay-network: